### ISSUE TITLE
Todo styling (refactor/themes branch)

### ISSUE THREAD

**Issue by jaccomeijer** [wheelroom/wheelroom#109]
- [x] Remove styling from modules (presets)
- [x] Make style trees consistent (container, wrapper, etc)
- [x] How to handle common styling like topicPreset in boilerplate theme
