### ISSUE TITLE
Todo split up into actual npm modules (refactor/themes branch)

### ISSUE THREAD

**Issue by jaccomeijer** [wheelroom/wheelroom#111]
- [ ] Move files
- [ ] Create package json for all modules
- [ ] Update dependencies in all modules
- [ ] Change all imports to the new modules
