### ISSUE TITLE
Update documentation in repo

### ISSUE THREAD

**Issue by jaccomeijer** [wheelroom/wheelroom#26]
Now that we refactored the full boilerplate, we must test and update the documentation.

## New sections
- [x] deployment, see #66 

## Main readme
- [main readme](https://github.com/wheelroom/wheelroom/blob/master/README.md)
- [x] All links on the page work
- [x] All content makes sense
- [x] Docs are complete
- [x] Remove the 'this is outdated' message

## Boilerplate
- [boilerplate readme](https://github.com/wheelroom/wheelroom/blob/master/packages/boilerplate/README.md)
- [x] Add netlify deploy badge
- [x] All links on the page work
- [x] All content makes sense
- [x] Docs are complete
- [x] Remove the 'this is outdated' message

### Getting started
- [getting-started](https://github.com/wheelroom/wheelroom/blob/master/packages/boilerplate/docs/getting-started.md)
- [x] All links on the page work
- [x] All content makes sense
- [x] Docs are complete
- [x] Test next step: edit page template
- [x] Test next step: change default locale
- [x] Test next step: add a new component
- [x] Test next step: auto fix with linter
- [x] Remove the 'this is outdated' message

### How it works
- [how-it-works](https://github.com/wheelroom/wheelroom/blob/master/packages/boilerplate/docs/how-it-works.md)
- [x] All links on the page work
- [x] All content makes sense
- [x] Docs are complete
- [x] Remove the 'this is outdated' message

## Roadmap
- [roadmap](https://github.com/wheelroom/wheelroom/blob/master/packages/boilerplate/docs/roadmap.md)
- [x] All links on the page work
- [x] All content makes sense
- [x] Docs are complete
- [x] Remove the 'this is outdated' message

**Comment by jaccomeijer** [comment]
A major refactor blocked this. That has been done. Now there's time to update the docs!

**Comment by jaccomeijer** [comment]
Move these to #69 

- [ ] wheels, how to use them
- [ ] templates, how to apply styling to wheels
- [ ] page sections, how to add a new variation
- [ ] svg, how to add svg from figma
